title: 'plotkine.github.io'
description: "Another infosec blog"
baseurl: "/"
url: "https://plotkine.github.io"

header_pages:
  - home.md
  - whoami.md
  - HTB-writeups.md
  - OSCP.md
  - js-games.md
  - js-anims.md

style: hacker

#footer: '<a href="https://github.com/plotkine">github</a>'

# Build settings
markdown: kramdown
remote_theme: Plotkine/jekyll-theme-console
