title: 'plotkine.github.io'
description: "Another infosec blog"
baseurl: "/"
url: "https://plotkine.github.io"

header_pages:
  - home.md
  - oscp.md
  - i3-gaps.md
  - kerberos.md
  - programming.md
  - schönheit.md
  - the-zen-way.md
  - music.md
  - contact.md
  - 1.md

style: hacker

#footer: '<a href="https://github.com/plotkine">github</a>'

# Build settings
markdown: kramdown
remote_theme: Plotkine/jekyll-theme-console
